src/protected/controllers/CustomerController.php
<?php

class CustomerController extends Controller
{
	// ----------------------------------------------------
	
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';
	public $assets_helper;
	
	// ----------------------------------------------------
	
	/**
	 * 初期化
	 */
	public function init() {
		parent::init();
		$this->assets_helper = new AssetsHelper( 'ControllerJS' );
	}
	
	// ----------------------------------------------------
	
	/**
	 * フォーム用アセット呼び出し
	 */
	protected function setAssetForm()
	{
		$this->assets_helper->set_js( 'ko.js', 'end' );
		$this->assets_helper->set_js( 'jquery.stringify.js', 'end' );
		$this->assets_helper->set_js( 'customer/form.js', 'end' );
		
	}
	// ----------------------------------------------------
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}
	
	// ----------------------------------------------------
	
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','view','create','update','admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	// ----------------------------------------------------
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new CustomerModel;
		
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		if(isset($_POST['CustomerModel']))
		{
			$model->attributes=$_POST['CustomerModel'];
			$model->create_date = date('Y-m-d H:i:s');
			$model->update_date = date('Y-m-d H:i:s');
			if($model->save())
			{
				$this->redirect(array('admin'));
			}
		}
		
		$this->setAssetForm();
		
		$this->render('create',array(
			'model'=>$model,
		));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		if(isset($_POST['CustomerModel']))
		{
			$model->attributes=$_POST['CustomerModel'];
			$model->update_date = date('Y-m-d H:i:s');
			if($model->save())
			{
				$this->redirect(array('admin'));
			}
		}
		
		
		$this->setAssetForm();
		$this->render('update',array(
			'model'=>$model
		));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
		
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->redirect(array('admin'));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new CustomerModel('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['CustomerModel']))
		{
			$model->attributes=$_GET['CustomerModel'];
		}
		
		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return CustomerModel the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=CustomerModel::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	
	// ----------------------------------------------------
	
	/**
	 * Performs the AJAX validation.
	 * @param CustomerModel $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='customer-model-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	// ----------------------------------------------------
}

src/protected/controllers/MatterController.php
<?php

class MatterController extends Controller
{
	// ----------------------------------------------------
	
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';
	
	public $assets_helper;


	// ----------------------------------------------------
	
	/**
	 * 初期化
	 */
	public function init() {
		parent::init();
		$this->assets_helper = new AssetsHelper( 'ControllerJS' );
	}
	
	// ----------------------------------------------------
	
	/**
	 * フォーム用アセット呼び出し
	 */
	protected function setAssetForm()
	{
		$this->assets_helper->set_js( 'ko.js', 'end' );
		$this->assets_helper->set_js( 'jquery.stringify.js', 'end' );
		$this->assets_helper->set_js( 'matter/form.js', 'end' );
		
	}
	// ----------------------------------------------------
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
		);
	}
	
	// ----------------------------------------------------
	
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array(
					'create','update', 'index','view', 'admin','delete',
					'save', 'DetailRemove', 'document'
				),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	// ----------------------------------------------------
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
	
	// ----------------------------------------------------
	
	/**
	 * Creates a new model.
	 * @param int $cid 顧客ID
	 */
	public function actionCreate( $cid )
	{
		$model=new MatterModel;
		
		/////バリデーション＆SAVE
		if(isset($_POST['MatterModel']))
		{
			
			$_POST['MatterModel']['est_date'] = null;
			$_POST['MatterModel']['est_date'] = null;
			$_POST['MatterModel']['receipt_date'] = null;
			
			
			$model->attributes=$_POST['MatterModel'];
			$model->create_date = date('Y-m-d H:i:s');
			$model->update_date = date('Y-m-d H:i:s');
			
			
			if($model->save())
			{
				$this->redirect(array('update','id'=>$model->id));
			}
			
		}
		//////ページGET
		else
		{
			$model->customer_id = $cid;
		}
		
		
		////顧客
		$customer = CustomerModel::model()->findByPk($cid);
		
		
		
		////関連変数
		$this->assets_helper->add_js(
			'var taxDetail = [];', 
			'var noTaxDetail = [];', 
			'end'
		);
		
		
		////アセット
		$this->setAssetForm();
		
		
		////レンダリング
		$this->render('create',array(
			'model'=>$model,
			'customer' => $customer,
		));
	}
	
	// ----------------------------------------------------
	
	/**
	 * 書類発行
	 * @param string $mode
	 */
	public function actionDocument( $id, $mode = 'bill' )
	{
		$matter = $this->loadModel($id);
		
		Yii::import('application.excel');
		spl_autoload_unregister(array('YiiBase','autoload'));
		Yii::import('application.excel.PHPExcel', true);
		spl_autoload_register(array('YiiBase','autoload')); 
		
		//$reader = PHPExcel_IOFactory::createReader('Excel2007');
		$reader = PHPExcel_IOFactory::createReader('Excel5');
		$excel = $reader->load(
					YiiBase::getPathOfAlias('application.excel_template')
						//. '/bill.xlsx'
						. '/bill.xls'
				);
		
		////親情報を登録
		$excel->setActiveSheetIndex(1);
		$sheet = $excel->getActiveSheet();
		
		//お客様情報
		$sheet->getCell('B1')->setValue( $matter->customer->company_name );
		$sheet->getCell('B2')->setValue( $matter->customer->company_honorific );
		$sheet->getCell('B3')->setValue( $matter->customer->name1 );
		$sheet->getCell('B4')->setValue( $matter->customer->name2 );
		$sheet->getCell('B5')->setValue( $matter->customer->kana1 );
		$sheet->getCell('B6')->setValue( $matter->customer->kana2 );
		$sheet->getCell('B7')->setValue( $matter->customer->honorific );
		$sheet->getCell('B8')->setValue( $matter->customer->pref );
		$sheet->getCell('B9')->setValue( $matter->customer->zip );
		$sheet->getCell('B10')->setValue( $matter->customer->address1 );
		$sheet->getCell('B11')->setValue( $matter->customer->address2 );
		$sheet->getCell('B12')->setValue( $matter->customer->address3 );
		$sheet->getCell('B13')->setValue( $matter->customer->tel1 );
		$sheet->getCell('B14')->setValue( $matter->customer->tel2 );
		$sheet->getCell('B15')->setValue( $matter->customer->fax );
		$sheet->getCell('B16')->setValue( $matter->customer->url );
		$sheet->getCell('B17')->setValue( $matter->customer->email1 );
		$sheet->getCell('B18')->setValue( $matter->customer->email2 );
		
		
		//帳票情報
		$sheet->getCell('B19')->setValue( $matter->est_date );
		$sheet->getCell('B20')->setValue( $matter->bill_date );
		$sheet->getCell('B21')->setValue( $matter->receipt_date );
		$sheet->getCell('B22')->setValue( $matter->delivery_document_date );
		$sheet->getCell('B23')->setValue( $matter->tax_subtotal );
		$sheet->getCell('B24')->setValue( $matter->tax_discount );
		$sheet->getCell('B25')->setValue( $matter->notax_subtotal );
		$sheet->getCell('B26')->setValue( $matter->notax_discount );
		$sheet->getCell('B27')->setValue( $matter->tax );
		$sheet->getCell('B28')->setValue( $matter->advanced_pay );
		$sheet->getCell('B29')->setValue( $matter->grand_total );
		$sheet->getCell('B30')->setValue( $matter->payment_total );
		$sheet->getCell('B31')->setValue( $matter->name );
		$sheet->getCell('B32')->setValue( $matter->est_remark );
		$sheet->getCell('B33')->setValue( $matter->bill_remark );
		$sheet->getCell('B34')->setValue( $matter->receipt_remark );
		$sheet->getCell('B35')->setValue( $matter->delivery_document_remark );
		
		
		
		////明細セル
		$excel->setActiveSheetIndex(2);
		$sheet = $excel->getActiveSheet();
		$taxFirstRow = $sheet->getCell('B1')->getValue();
		$taxCell = $sheet->getCell('B2')->getValue();
		$taxRemarksCell = $sheet->getCell('B3')->getValue();
		$taxPriceCell = $sheet->getCell('B4')->getValue();
		$taxQtyCell = $sheet->getCell('B5')->getValue();
		$taxUnitCell = $sheet->getCell('B6')->getValue();
		$taxSubtotalCell = $sheet->getCell('B7')->getValue();
		$notaxFirstRow = $sheet->getCell('B8')->getValue();
		$notaxCell = $sheet->getCell('B9')->getValue();
		$notaxRemarksCell = $sheet->getCell('B10')->getValue();
		$notaxPriceCell = $sheet->getCell('B11')->getValue();
		$notaxQtyCell = $sheet->getCell('B12')->getValue();
		$notaxUnitCell = $sheet->getCell('B13')->getValue();
		$notaxSubtotalCell = $sheet->getCell('B14')->getValue();
		
		$excel->setActiveSheetIndex(0);
		$sheet = $excel->getActiveSheet();
		
		
		//課税項目明細
		$startCell = $taxFirstRow;
		$add = 0;
		foreach( $matter->taxDetail as $detail )
		{
			$sheet->insertNewRowBefore( $startCell+1, 1 );
			$this->copyRows( $sheet, $taxFirstRow, $startCell, 1, 6 );
			$sheet->getCell($taxCell.$startCell)->setValue( $detail->name );
			$sheet->getCell($taxRemarksCell.$startCell)->setValue( $detail->remark );
			$sheet->getCell($taxPriceCell.$startCell)->setValue( $detail->price );
			$sheet->getCell($taxQtyCell.$startCell)->setValue( $detail->qty );
			$sheet->getCell($taxUnitCell.$startCell)->setValue( $detail->qty_unit );
			$sheet->getCell($taxSubtotalCell.$startCell)->setValue( $detail->sub_total );
			$startCell ++ ;
			$add ++ ;
		}
		$sheet->removeRow($startCell);
		
		//非課税項目明細
		$startCell2 = $notaxFirstRow + ($add-1);
		foreach( $matter->noTaxDetail as $detail )
		{
			$sheet->insertNewRowBefore( $startCell2+1, 1 );
			$this->copyRows( $sheet, ($notaxFirstRow + ($add-1)), $startCell2, 1, 6 );
			$sheet->getCell($notaxCell.$startCell2)->setValue( $detail->name );
			$sheet->getCell($notaxRemarksCell.$startCell2)->setValue( $detail->remark );
			$sheet->getCell($notaxPriceCell.$startCell2)->setValue( $detail->price );
			$sheet->getCell($notaxQtyCell.$startCell2)->setValue( $detail->qty );
			$sheet->getCell($notaxUnitCell.$startCell2)->setValue( $detail->qty_unit );
			$sheet->getCell($notaxSubtotalCell.$startCell2)->setValue( $detail->sub_total );
			$startCell2 ++ ;
		}
		$sheet->removeRow($startCell2);
		
		
		//保存
		$excel->setActiveSheetIndex(0);
		ini_set('memory_limit', '2048M'); set_time_limit('1200');
		$writer = PHPExcel_IOFactory::createWriter($excel, 'Excel2007');
		//$writer = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
		$path = YiiBase::getPathOfAlias('application.excel_template') . '/test.xlsx';
		//$path = YiiBase::getPathOfAlias('application.excel_template') . '/test.xls';
		$writer->save(
			$path
		);
		
		//ダウンロード
		$fileName = $matter->id . '_' . $mode . '_' .date('Y-m-d_H-i-s'). '.xlsx';
		header("Content-Type: application/octet-stream");
		header("Content-Disposition: attachment; filename=". $fileName);
		echo file_get_contents( $path );
		
		unlink($path);
		
	}
	
	// ----------------------------------------------------
	
	/**
	 * エクセル行コピー
	 */
	public function copyRows(
		$sheet,//シート情報
		$srcRow,	// 複製元行番号
		$dstRow,	// 複製先行番号
		$height, 	// 複製行数
		$width		// 複製カラム数
	) {
		
		for($row=0; $row<$height; $row++) {
			// セルの書式と値の複製
			for ($col=0; $col<$width; $col++) {
				$cell = $sheet->getCellByColumnAndRow($col, $srcRow+$row);
				$style = $sheet->getStyleByColumnAndRow($col, $srcRow+$row);
				
				$dstCell = PHPExcel_Cell::stringFromColumnIndex($col).(string)($dstRow+$row);
				$sheet->setCellValue($dstCell, $cell->getValue());
				$sheet->duplicateStyle($style, $dstCell);
			}
			
			// 行の高さ複製。
			$h = $sheet->getRowDimension($srcRow+$row)->getRowHeight();
			$sheet->getRowDimension($dstRow+$row)->setRowHeight($h);
		}
		
		// セル結合の複製
		// - $mergeCell="AB12:AC15" 複製範囲の物だけ行を加算して復元。 
		// - $merge="AB16:AC19"
		foreach ($sheet->getMergeCells() as $mergeCell) {
			$mc = explode(":", $mergeCell);
			$col_s = preg_replace("/[0-9]*/" , "",$mc[0]);

src/protected/views/customer/_search.php
<?php
/* @var $this CustomerController */
/* @var $model CustomerModel */
/* @var $form CActiveForm */
?>

<div class="wide">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="">
		<?php echo $form->label($model,'company_name'); ?>
		<?php echo $form->textField($model,'company_name',array('class' => 'form-control')); ?>
	</div>
	
	<div class="">
		<div class="col-md-6">
			<?php echo $form->label($model,'name1'); ?>
			<?php echo $form->textField($model,'name1',array('class' => 'form-control')); ?>
		</div>
		<div class="col-md-6">
			<?php echo $form->label($model,'name2'); ?>
			<?php echo $form->textField($model,'name2',array('class' => 'form-control')); ?>
		</div>
	</div>
	
	<div class="">
		<div class="col-md-6">
			<?php echo $form->label($model,'kana1'); ?>
			<?php echo $form->textField($model,'kana1',array('class' => 'form-control')); ?>
		</div>
		<div class="col-md-6">
			<?php echo $form->label($model,'kana2'); ?>
			<?php echo $form->textField($model,'kana2',array('class' => 'form-control')); ?>
		</div>
	</div>
	
	<div class="">
		<div class="col-md-6">
			<?php echo $form->label($model,'tel1'); ?>
			<?php echo $form->textField($model,'tel1',array('class' => 'form-control')); ?>
		</div>
		<div class="col-md-6">
			<?php echo $form->label($model,'tel2'); ?>
			<?php echo $form->textField($model,'tel2',array('class' => 'form-control')); ?>
		</div>
	</div>
	<div class="">
		<?php echo $form->label($model,'fax'); ?>
		<?php echo $form->textField($model,'fax',array('class' => 'form-control')); ?>
	</div>
	
	<div class="">
		<?php echo $form->label($model,'url'); ?>
		<?php echo $form->textField($model,'url',array('class' => 'form-control')); ?>
	</div>
	
	<div class="">
		<?php echo $form->label($model,'email1'); ?>
		<?php echo $form->textField($model,'email1',array('class' => 'form-control')); ?>
	</div>
	
	<div class="">
		<?php echo $form->label($model,'email2'); ?>
		<?php echo $form->textField($model,'email2',array('class' => 'form-control')); ?>
	</div>
	
	<div class="buttons">
		<?php echo CHtml::submitButton('検索',array('class' => 'btn btn-success')); ?>
		<?php echo CHtml::link( '検索解除', Yii::app()->createUrl('customer/admin'), array('class' => 'btn btn-danger') ); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

src/protected/views/customer/_view.php
<?php
/* @var $this CustomerController */
/* @var $data CustomerModel */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('company_name')); ?>:</b>
	<?php echo CHtml::encode($data->company_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('company_honorific')); ?>:</b>
	<?php echo CHtml::encode($data->company_honorific); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name1')); ?>:</b>
	<?php echo CHtml::encode($data->name1); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name2')); ?>:</b>
	<?php echo CHtml::encode($data->name2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('honorific')); ?>:</b>
	<?php echo CHtml::encode($data->honorific); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('kana1')); ?>:</b>
	<?php echo CHtml::encode($data->kana1); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('kana2')); ?>:</b>
	<?php echo CHtml::encode($data->kana2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('zip')); ?>:</b>
	<?php echo CHtml::encode($data->zip); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address1')); ?>:</b>
	<?php echo CHtml::encode($data->address1); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address2')); ?>:</b>
	<?php echo CHtml::encode($data->address2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address3')); ?>:</b>
	<?php echo CHtml::encode($data->address3); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tel1')); ?>:</b>
	<?php echo CHtml::encode($data->tel1); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tel2')); ?>:</b>
	<?php echo CHtml::encode($data->tel2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fax')); ?>:</b>
	<?php echo CHtml::encode($data->fax); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('url')); ?>:</b>
	<?php echo CHtml::encode($data->url); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email1')); ?>:</b>
	<?php echo CHtml::encode($data->email1); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email2')); ?>:</b>
	<?php echo CHtml::encode($data->email2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('remark')); ?>:</b>
	<?php echo CHtml::encode($data->remark); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_date')); ?>:</b>
	<?php echo CHtml::encode($data->create_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_date')); ?>:</b>
	<?php echo CHtml::encode($data->update_date); ?>
	<br />

	*/ ?>

</div>

src/protected/views/customer/admin.php
<?php
/* @var $this CustomerController */
/* @var $model CustomerModel */

$this->breadcrumbs=array(
	'Customer Models'=>array('index'),
	'Manage',
);

$this->menu=array();

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#customer-model-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>顧客管理</h1>

<hr />
<?php echo CHtml::link( '新規顧客情報作成', $this->createUrl('create'), array('class' => 'btn btn-primary' ) ); ?>
<hr />

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div>

<hr />

<?php $dataProvider = $model->search(); ?>


<?php foreach( $dataProvider->getData() as $data ):?>
	<table class="table table-striped table-bordered">
		<tr>
			<th>企業名<br />顧客名</th>
			<th>住所</th>
			<th>電話<br />FAX</th>
			<th>URL/Eメール</th>
			<th>備考</th>
			<th>操作</th>
		</tr>
		<tr>
			<td>
				<?php echo $data->company_name; ?><?php echo $data->company_honorific; ?><br/>
				<?php echo $data->name1; ?> <?php echo $data->name2; ?> <?php echo $data->honorific; ?><br />
				<?php echo $data->kana1; ?> <?php echo $data->kana2; ?> <?php echo $data->honorific; ?>
			</td>
			<td>
				<?php echo $data->zip; ?><br />
				<?php echo $data->pref; ?><br />
				<?php echo $data->address1; ?><br />
				<?php echo $data->address2; ?><br />
				<?php echo $data->address3; ?>
			</td>
			<td>
				<?php echo $data->tel1; ?><br />
				<?php echo $data->tel2; ?><br />
				<?php echo $data->fax; ?>
			</td>
			<td>
				<?php echo $data->url; ?><br />
				<?php echo $data->email1; ?><br />
				<?php echo $data->email2; ?>
			</td>
			<td>
				<?php echo $data->remark; ?>
			</td>

			<td class="alingCenter">
				<?php echo CHtml::link(
						'詳細／編集',
						Yii::app()->createUrl('customer/update',array('id'=>$data->id)),
						array(
							'class' => 'btn btn-primary'
							)
					);
				?><br />
				<?php
					echo CHtml::link(
						'案件作成',
						Yii::app()->createUrl('matter/create',array('cid'=>$data->id)),
						array('class' => 'btn btn-primary')
					);
				?>
			</td>
		</tr>
		<tr>
			<th colspan="6">案件</th>
		</tr>
		<tr>
			<td colspan="6">
				<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>案件名</th>
							<th>作成日</th>
							<th>合計金額</th>
							<th>ステータス</th>
							<th>支払いステータス</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach( $data->matter as $matter ): ?>
							<tr>
								<td><?php echo $matter->name; ?></td>
								<td><?php echo $matter->create_date; ?></td>
								<td>
									<?php echo number_format($matter->grand_total); ?>円</td>
								</td>
								<td>
									<?php if(is_null($matter->statusMaster)): ?>
										未設定
									<?php else: ?>
										<?php echo $matter->statusMaster->name; ?>
									<?php endif; ?>
								</td>
								<td>
									<?php if(is_null($matter->paymentStatusMaster)): ?>
										未設定
									<?php else: ?>
										<?php echo $matter->paymentStatusMaster->name; ?>
									<?php endif; ?>
								</td>
								<td>
									<?php
										echo CHtml::link(
											'詳細', 
											Yii::app()->createUrl('matter/update', array('id' => $matter->id ) ),
											array(
												'class' => 'btn btn-primary'
											)
										);
									?>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</td>
		</tr>
	</table>
	
	<hr />
<?php endforeach; ?>


<hr />
<?php
$this->widget(
	'CLinkPager',
	array(
		'pages' => $dataProvider->getPagination(),
	)
);?>

src/protected/views/customer/create.php
<?php
/* @var $this CustomerController */
/* @var $model CustomerModel */

$this->breadcrumbs=array(
	'Customer Models'=>array('index'),
	'Create',
);

$this->menu=array();
?>

<h1>顧客情報作成</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

src/protected/views/customer/index.php
<?php
/* @var $this CustomerController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Customer Models',
);

$this->menu=array(
	array('label'=>'Create CustomerModel', 'url'=>array('create')),
	array('label'=>'Manage CustomerModel', 'url'=>array('admin')),
);
?>

<h1>Customer Models</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>